app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    # Line 友達追加のWeb hook
    path('callback/', views.callback, name='callback'),

    path('', views.LineUserList.as_view(), name='line_user_list'),
    path('detail/<int:pk>/', views.LineMessageList.as_view(), name='line_message_list'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
from django.utils import timezone


class LinePush(models.Model):
    """Lineでのプッシュ先を表す"""
    user_id = models.CharField('ユーザーID', max_length=100, unique=True)
    display_name = models.CharField('表示名', max_length=255, blank=True)

    def __str__(self):
        return self.display_name


class LineMessage(models.Model):
    """Lineの各メッセージを表現する"""
    push = models.ForeignKey(LinePush, verbose_name='プッシュ先', on_delete=models.SET_NULL, blank=True, null=True)
    text = models.TextField('テキスト')
    is_admin = models.BooleanField('このメッセージは管理者側の発言か', default=True)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return f'{self.push} - {self.text[:10]} - {self.is_admin}'


app/views.py
import json
from django.http import HttpResponse
from django.shortcuts import redirect, get_object_or_404
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from .models import LinePush, LineMessage
import linebot
from linebot.models import TextSendMessage


line_bot_api = linebot.LineBotApi('アクセストークン')


@csrf_exempt
def callback(request):
    """ラインの友達追加時・メッセージ受信時に呼ばれる"""
    if request.method == 'POST':
        request_json = json.loads(request.body.decode('utf-8'))
        events = request_json['events']
        line_user_id = events[0]['source']['userId']

        # チャネル設定のWeb hook接続確認時にはここ。このIDで見に来る。
        if line_user_id == 'Udeadbeefdeadbeefdeadbeefdeadbeef':
            pass

        # 友達追加時
        elif events[0]['type'] == 'follow':
            profile = line_bot_api.get_profile(line_user_id)
            LinePush.objects.create(user_id=line_user_id, display_name=profile.display_name)

        # アカウントがブロックされたとき
        elif events[0]['type'] == 'unfollow':
            LinePush.objects.filter(user_id=line_user_id).delete()

        # メッセージ受信時
        elif events[0]['type'] == 'message':
            text = request_json['events'][0]['message']['text']
            line_push = get_object_or_404(LinePush, user_id=line_user_id)
            LineMessage.objects.create(push=line_push, text=text, is_admin=False)

    return HttpResponse()


class LineUserList(generic.ListView):
    model = LinePush
    template_name = 'app/line_user_list.html'


class LineMessageList(generic.CreateView):
    model = LineMessage
    fields = ('text',)
    template_name = 'app/line_message_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        line_push = get_object_or_404(LinePush, pk=self.kwargs['pk'])
        context['message_list'] = LineMessage.objects.filter(push=line_push)
        context['push'] = line_push
        return context

    def form_valid(self, form):
        line_push = get_object_or_404(LinePush, pk=self.kwargs['pk'])
        message = form.save(commit=False)
        message.push = line_push
        message.is_admin = True
        message.save()
        line_bot_api.push_message(line_push.user_id, messages=TextSendMessage(text=message.text))
        return redirect('app:line_message_list', pk=line_push.pk)

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ライン</title>
    {% block extrahead %}{% endblock %}
    <style>
        * {
            margin: 0;
        }

        body {
            width: 960px;
            margin: 0 auto;
        }


        header > img {
            width: 100px;
            height: 100px;
        }


        main {
            display: grid;
            grid-column: 1fr 1fr;
        }

        main > h1 {
            margin-bottom: 30px;
            text-align: center;
            grid-column: 1 / -1;
        }


        .right {
            grid-column: 1 / -1;
            justify-self: end;
        }

        .left {
            grid-column: 1 / -1;

        }

        .card {
            padding: 20px;
            box-shadow: 0 1px 6px #ccc;
            border-radius: 8px;
            width: 50%;
            margin-bottom: 10px;
        }

        body > form {
            position: fixed;
            bottom: 0;
        }

        textarea {
            height: 100px;
        }
    </style>
</head>
<body>
<header><img src="{% static 'app/lineqr.png' %}"></header>
<main>{% block content %}{% endblock %}</main>
</body>
</html>

app/templates/app/line_message_list.html
{% extends 'app/base.html' %}


{% block content %}
    <h1>{{ push.display_name }} チャット</h1>
    {% for message in message_list %}
        {% if message.is_admin %}
            <div class="card right">
        {% else %}
            <div class="card left">
        {% endif %}
    {{ message.text }} - {{ message.created_at }}
    </div>
    {% endfor %}

    <form action="" method="POST">
        {{ form.as_p }}
        <button type="submit">送信</button>
        {% csrf_token %}
    </form>
{% endblock %}

app/templates/app/line_user_list.html
{% extends 'app/base.html' %}


{% block content %}
    <h1>Lineユーザーリスト</h1>
    {% for line_user in linepush_list %}
        <p><a href="{% url 'app:line_message_list' line_user.pk %}">{{ line_user }}</p>
    {% endfor %}
{% endblock %}